export const orderList = [
  {
    id: 1,
    type: '배송/방문수령',
    orderDate: '2022.08.04',
    orderStatus: '결제완료',
    totalPrice: 164000,
    orderItems: [
      {
        itemId: '1',
        shopName: '써머슈슈즈',
        itemName: '로토 스르르트 썸머 슈즈',
        imgUrl: '',
        option: ['화이트/275'],
        quantity: 1,
        price: 82000,
        isReviewed: false,
      },
      {
        itemId: '2',
        shopName: '써머슈슈즈',
        itemName: '로토 스르르트 썸머 슈즈',
        imgUrl: '',
        option: ['블랙/270'],
        quantity: 1,
        price: 82000,
        isReviewed: false,
      },
    ],
  },
  {
    id: 2,
    type: '배달/픽업',
    orderDate: '2022.08.05',
    orderStatus: '결제완료',
    totalPrice: 21500,
    orderItems: [
      {
        itemId: '2',
        shopName: 'BBK치킨',
        itemName: '뿌린클 순살치킨세트',
        imgUrl: '',
        option: ['제로콜라', '살사소스 (+500원)'],
        quantity: 1,
        price: 21500,
        isReviewed: false,
      },
    ],
  },
  {
    id: 3,
    type: '예약',
    orderDate: '2022.08.06',
    orderStatus: '결제완료',
    totalPrice: 50000,
    orderItems: [
      {
        itemId: '3',
        shopName: '컬러리스트퍼스널',
        itemName: '퍼스널컬러 진단',
        imgUrl: '',
        option: ['3대1 60분'],
        reservationDate: '2022.08.08(월), 오후 8:00',
        numOfPeople: 3,
        quantity: 1,
        price: 50000,
        isReviewed: false,
      },
    ],
  },
];
